"use client";
import { useEffect, useState } from "react";
import { Loader2, X } from "lucide-react";
import { API_BASE_URL } from "@/lib/api";
const money=(n)=>"Rp "+Number(n||0).toLocaleString("id-ID");
export default function DrinkCustomizer({product,onClose,onAdd}){
 const [config,setConfig]=useState(null),[loading,setLoading]=useState(true),[mood,setMood]=useState(null),[size,setSize]=useState(null),[sugar,setSugar]=useState(null),[addonIds,setAddonIds]=useState([]);
 useEffect(()=>{let live=true;fetch(`${API_BASE_URL}/api/customization/products/${product.id}`).then(r=>r.json()).then(j=>{if(!live)return;const c=j.data;setConfig(c);if(!c?.enabled){onAdd(product,null,Number(product.price));return;} if(c.mood_enabled)setMood(c.moods.hot?'Hot':'Cold');if(c.size_enabled)setSize('Medium');if(c.sugar_enabled)setSugar('Normal Sugar');setLoading(false)}).catch(()=>{if(live){alert('Gagal memuat opsi minuman.');onClose();}});return()=>{live=false};},[product,onAdd,onClose]);
 if(loading)return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/40"><Loader2 className="animate-spin text-white"/></div>;
 const addons=config.addons.filter(a=>addonIds.includes(a.id));const total=(config.size_enabled?Number(config.sizes[size]):Number(product.price))+addons.reduce((s,a)=>s+Number(a.price),0);
 const choice=(label,values,current,setter,priceMap)=> <section><p className="mb-2 text-xs font-black uppercase tracking-wider text-[#797676]">{label}</p><div className="flex flex-wrap gap-2">{values.map(v=><button key={v} onClick={()=>setter(v)} className={`rounded-xl px-3 py-2 text-xs font-bold ${current===v?'bg-[#D4A373] text-white':'bg-[#F9F9F9] text-[#797676] shadow-[3px_3px_7px_rgba(0,0,0,.08)]'}`}>{v}{priceMap&&` · ${money(priceMap[v])}`}</button>)}</div></section>;
 return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/40 p-3 sm:items-center"><div className="w-full max-w-lg rounded-[28px] bg-[#F9F9F9] p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h2 className="font-montserrat text-xl font-black">{product.name}</h2><p className="text-xs text-[#797676]">Sesuaikan minuman Anda</p></div><button onClick={onClose}><X/></button></div><div className="space-y-5">{config.mood_enabled&&choice('Mood',[...(config.moods.hot?['Hot']:[]),...(config.moods.cold?['Cold']:[])],mood,setMood)}{config.size_enabled&&choice('Size',['Medium','Large','Jumbo'],size,setSize,config.sizes)}{config.sugar_enabled&&choice('Sugar',['Normal Sugar','Less Sugar','No Sugar'],sugar,setSugar)}{config.addons_enabled&&config.addons.length>0&&<section><p className="mb-2 text-xs font-black uppercase tracking-wider text-[#797676]">Add-on</p><div className="grid grid-cols-2 gap-2">{config.addons.map(a=><button key={a.id} onClick={()=>setAddonIds(x=>x.includes(a.id)?x.filter(i=>i!==a.id):[...x,a.id])} className={`rounded-xl p-3 text-left text-xs ${addonIds.includes(a.id)?'bg-[#D4A373]/15 text-[#1A1A1A] ring-1 ring-[#D4A373]':'bg-white'}`}><b>{a.name}</b><span className="block text-[#D4A373]">+{money(a.price)}</span></button>)}</div></section>}<button onClick={()=>onAdd(product,{mood,size,sugar,addon_ids:addonIds},total)} className="w-full rounded-2xl bg-[#D4A373] py-4 text-sm font-black text-white">Tambahkan · {money(total)}</button></div></div></div>;
}
